name: play_turf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  sizer: 2.0.15
  lottie: 1.3.0
  smooth_page_indicator: 1.0.0+2
  carousel_slider: 4.1.1
  google_fonts: 3.0.1
  dio: 4.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/json/
    - asset/images/onboarding_images/
    - asset/images/login/
    - asset/images/favorites/
    - asset/images/turf/
  uses-material-design: true

